route/categorie/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, DecimalField, SelectField, IntegerField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError, NumberRange
from wtforms.widgets import html5 as h5widgets
from wtforms.fields import html5
from flask_login import current_user
from route.models import User, Categorie

class CatForm(FlaskForm):
    nom = StringField('Nom', 
                            validators=[DataRequired(), Length(min=2 , max=20)])
    heure_hebdo = IntegerField('Heure Hebdo', 
                            validators=[DataRequired(), NumberRange(min=1)],
                            widget=h5widgets.NumberInput(min=1))
    salaire_hebdo = DecimalField('Salaire Hebdo', validators=[DataRequired(), NumberRange(min=1)])
    liste_jour = StringField('Liste Jour', 
                            validators=[DataRequired()])

    submit = SubmitField('Ajouter')

route/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, DecimalField, SelectField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError, NumberRange
from wtforms.widgets import html5 as h5widgets
from wtforms.fields import html5
from flask_login import current_user
from route.models import User, Categorie


class RegistrationForm(FlaskForm):
    matricule = StringField('Matricule', 
                            validators=[DataRequired(), Length(min=2 , max=20)])
    nom = StringField('Nom', 
                            validators=[DataRequired(), Length(min=2 , max=20)])
    prenom = StringField('Prenom', 
                            validators=[DataRequired(), Length(min=2 , max=20)])
    date_naissance = html5.DateField('Date Naissance', 
                            validators=[DataRequired()])
    date_embauche = html5.DateField('Date Embauche', 
                            validators=[DataRequired()])
    date_fin_contrat = html5.DateField('Date Fin Contrat', 
                            validators=[DataRequired()])

    type_user = SelectField('type', choices=[('1', 'Admin'), ('0', 'Normal')])
    idcategorie = QuerySelectField('Categorie', query_factory=lambda: Categorie.query.all())
    password = PasswordField('Password', validators=[DataRequired()])

    submit = SubmitField('Sign Up')

    def validate_matricule(self, matricule):
        user = User.query.filter_by(matricule=matricule.data).first()
        if user:
            raise ValidationError('That matricule is taken. Please choose a different one')

class UpdateForm(FlaskForm):
    matricule = StringField('Matricule', 
                            validators=[DataRequired(), Length(min=2 , max=20)])
    nom = StringField('Nom', 
                            validators=[DataRequired(), Length(min=2 , max=20)])
    prenom = StringField('Prenom', 
                            validators=[DataRequired(), Length(min=2 , max=20)])
    date_naissance = html5.DateField('Date Naissance', 
                            validators=[DataRequired()])
    date_embauche = html5.DateField('Date Embauche', 
                            validators=[DataRequired()])
    date_fin_contrat = html5.DateField('Date Fin Contrat', 
                            validators=[DataRequired()])

    type_user = SelectField('type', choices=[('1', 'Admin'), ('0', 'Normal')])
    idcategorie = QuerySelectField('Categorie', query_factory=lambda: Categorie.query.all())
    password = PasswordField('Password', validators=[DataRequired()])

    submit = SubmitField('Sign Up')

    

    
class LoginForm(FlaskForm):
    matricule = StringField('Matricule', 
                            validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Login')

route/categorie/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from route.models import Categorie
from route.categorie.forms import CatForm
from route import db
from route.config import Default


categorie = Blueprint('categorie', __name__)


@categorie.route('/categorie')
@login_required
def cat():
    page = request.args.get('page', 1, type=int)
    cats = Categorie.query.paginate(page=page, per_page=5)
    return render_template('categorie.html', title='Listes categories', cats=cats)

@categorie.route('/categorie/add', methods=['GET', 'POST'])
@login_required
def add_cat():
    form = CatForm()
    if form.validate_on_submit():
        indemnite = float(form.salaire_hebdo.data) * Default.TAUX_INDEMNITE
        cat = Categorie(nom=form.nom.data,
                    heure_hebdo=form.heure_hebdo.data,
                    salaire_hebdo=form.salaire_hebdo.data,
                    indemnite=indemnite,
                    liste_jour=form.liste_jour.data)
        db.session.add(cat)
        db.session.commit()
        flash(f'Categorie created', 'success')
        return redirect(url_for('categorie.cat'))
    return render_template('categorie_form.html', title='Ajout categorie', form=form)

@categorie.route('/categorie/<int:cat_id>/update', methods=['GET', 'POST'])
@login_required
def updateCat(cat_id):
    cat = Categorie.query.get_or_404(cat_id)
    form = CatForm()
    if form.validate_on_submit():
        cat.nom = form.nom.data
        cat.heure_hebdo = form.heure_hebdo.data
        cat.salaire_hebdo = form.salaire_hebdo.data
        indemnite = float(form.salaire_hebdo.data) * Default.TAUX_INDEMNITE
        cat.indemnite = indemnite
        cat.liste_jour = form.liste_jour.data

        db.session.commit()
        flash('Your categorie has been updated!', 'success')
        return redirect(url_for('categorie.cat'))
    else:
        form.nom.data = cat.nom
        form.heure_hebdo.data = cat.heure_hebdo
        form.salaire_hebdo.data = cat.salaire_hebdo
        form.liste_jour.data = cat.liste_jour
    return render_template('categorie_form.html', title='Update employe', form=form, legend='Update employe')

@categorie.route('/categorie/<int:cat_id>/delete', methods=['GET', 'POST'])
@login_required
def deleteCat(cat_id):
    cat = Categorie.query.get_or_404(cat_id)
    db.session.delete(cat)
    db.session.commit()
    flash('Your categorie has been deleted!', 'success')
    return redirect(url_for('categorie.cat'))

route/configuration/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from route.models import Pointage, Detailpointage, User, Config
from route.configuration.forms import ConfigForm
from route import db
from route.config import Default
from route.pointage import services


configuration = Blueprint('configuration', __name__)

@configuration.route('/config', methods=['GET', 'POST'])
@login_required
def list_config():
    configs = Config.query.all()
    return render_template('config.html', title='Listes config', configs=configs)



@configuration.route('/configuration/<int:config_id>/update', methods=['GET', 'POST'])
@login_required
def updateConfig(config_id):
    config = Config.query.get_or_404(config_id)
    form = ConfigForm()
    if form.validate_on_submit():
        config.cle = form.cle.data
        config.description = form.description.data
        config.valeur = form.valeur.data

        db.session.commit()
        flash('Your configuration has been updated!', 'success')
        return redirect(url_for('configuration.list_config'))
    else:
        form.cle.data = config.cle
        form.description.data = config.description
        form.valeur.data = config.valeur
    return render_template('config_form.html', title='Update config', form=form, legend='Update config')

route/main/routes.py
from flask import render_template, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from route.pointage import services

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    services.paie_total()
    return render_template('home.html', title='Gestion Route', cur=current_user)


@main.route('/about')
def about():
    return render_template('about.html', title='About')

route/pointage/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from route.models import Pointage, Detailpointage, User
# from route.pointage.forms import CatForm
from route import db
from route.config import Default
from route.pointage import services


pointage = Blueprint('pointage', __name__)

@pointage.route('/pointage/list', methods=['GET', 'POST'])
@login_required
def list_pointage():
    page = request.args.get('page', 1, type=int)
    points = Pointage.query.paginate(page=page, per_page=10)
    return render_template('list_pointage.html', title='Listes pointages', points=points)



@pointage.route('/pointage', methods=['GET', 'POST'])
@login_required
def add_pointage():
    days = Default.DAYS
    return render_template('pointage.html', title='Listes categories', days=days)

@pointage.route('/pointage/<int:user_id>', methods=['GET', 'POST'])
@login_required
def insert_pointage(user_id):
    days = Default.DAYS
    ferie = {}
    jour = {}
    nuit = {}
    for key in request.form:
        name, typ = key.split("_")
        if typ == 'ferie':
            ferie[name] = request.form.get(key)
        if typ == 'jour':
            jour[name] = request.form.get(key)
        if typ == 'nuit':
            nuit[name] = request.form.get(key)

    pointage = Pointage.query.filter_by(iduser=user_id).first()
    if pointage == None:
        pointage_id = services.insertdb_pointage(user_id, ferie, jour, nuit)
    else:
        pointage_id = services.updatedb_pointage(user_id, ferie, jour, nuit)
    return redirect(url_for('pointage.calcul_heure', user_id=user_id, pointage_id=pointage_id))

@pointage.route('/pointage/<int:user_id>/calcul/<int:pointage_id>', methods=['GET', 'POST'])
@login_required
def calcul_heure(user_id, pointage_id):
    user = User.query.get_or_404(user_id)
    pointage = Pointage.query.get_or_404(pointage_id)
    res = services.calcul_heure(user, pointage)
    return render_template('heure_semaine.html', title="Calcul heure", user=user, results=res, pointage=pointage)

@pointage.route('/pointage/<int:user_id>/fiche-de-paie/<int:pointage_id>', methods=['GET', 'POST'])
@login_required
def fiche_paie(user_id, pointage_id):
    user = User.query.get_or_404(user_id)
    pointage = Pointage.query.get_or_404(pointage_id)
    paie, indemnite, total_paye, total_with_impot, total_without_impot = services.fiche_de_paie(user, pointage)
    # return render_template('home.html')
    return render_template('fiche_paie.html', title="Fiche de paie", user=user, results=paie,
                                            indemnite=indemnite, total_paye=total_paye, total_with_impot=total_with_impot,total_without_impot=total_without_impot)

@pointage.route('/user/stat')
@login_required
def stat_user():
    u, t = services.users_total()
    return render_template('stat.html', title="Statistiques employees", users=u, total=t)

@pointage.route('/user/stat/detail')
@login_required
def detail_stat_user():
    details = services.paie_total()
    return render_template('stat_detail.html', title="Statistiques", details=details)

route/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from route import db, bcrypt
from route.models import User
from route.users.forms import RegistrationForm, LoginForm, UpdateForm
import route.users.utils as utils

users = Blueprint('users', __name__)


@users.route('/user')
@login_required
def user():
    page = request.args.get('page', 1, type=int)
    users = User.query.paginate(page=page, per_page=10)
    return render_template('user.html', title='Listes user', users=users, utils=utils)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(matricule=form.matricule.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(matricule=form.matricule.data,
                    nom=form.nom.data,
                    prenom=form.prenom.data,
                    date_naissance=form.date_naissance.data,
                    date_embauche=form.date_embauche.data,
                    date_fin_contrat=form.date_fin_contrat.data,
                    type_user=form.type_user.data,
                    idcategorie=form.idcategorie.data.id,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.nom.data}', 'success')
        return redirect(url_for('users.user'))
    return render_template('register.html', title='Register', form=form)

@users.route('/user/<int:user_id>/update', methods=['GET', 'POST'])
@login_required
def updateUser(user_id):
    user = User.query.get_or_404(user_id)
    form = UpdateForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.nom = form.nom.data
        user.prenom = form.prenom.data
        user.date_naissance = form.date_naissance.data
        user.date_embauche = form.date_embauche.data
        user.date_fin_contrat = form.date_fin_contrat.data
        user.type_user = form.type_user.data
        user.idcategorie = form.idcategorie.data.id
        user.password = hashed_password

        db.session.commit()
        flash('Your portion has been updated!', 'success')
        return redirect(url_for('users.user'))
    else:
        form.matricule.data = user.matricule
        form.nom.data = user.nom
        form.prenom.data = user.prenom
        form.date_naissance.data = user.date_naissance
        form.date_embauche.data = user.date_embauche
        form.date_fin_contrat.data = user.date_fin_contrat
        form.type_user.data = user.type_user
        form.idcategorie.data = user.idcategorie
    return render_template('register.html', title='Update employe', form=form, legend='Update employe')

route/templates/about.html
{% extends "layout.html" %}
{% block content %}
		<h1>About</h1>
		<p>Created by Yu</p>
{% endblock content %}

route/templates/categorie.html
{% extends "layout.html" %}
{% block content %}
	<h1>Listes des categories</h1>
	<table class="table">
		<thead>
		<tr>
		  <th scope="col">#</th>
		  <th scope="col">Nom</th>
		  <th scope="col">Heure hebdo</th>
		  <th scope="col">Salaire hebdo</th>
		  <th scope="col">Indemnite</th>
		  <th scope="col">Liste jour</th>
		</tr>
		</thead>
		<tbody>
		{% for cat in cats.items %}
		<tr>
		  <td>{{cat.id}}</td>
		  <td>{{cat.nom}}</td>
		  <td>{{cat.heure_hebdo}}</td>
		  <td>{{cat.salaire_hebdo}}</td>
		  <td>{{cat.indemnite}}</td>
		  <td>{{cat.liste_jour}}</td>
		  {% if current_user.is_authenticated and current_user.type_user == 1 %}
		  <!-- url_for('trajet.update_trajet', portion_id=route.idportionroute) 
		  url_for('users.user_update', iduser=user.id)-->
		  <td><a class="btn btn-outline-success" href="{{url_for('categorie.updateCat', cat_id=cat.id)}}">Modifier</a></td>
		  <td><a class="btn btn-outline-danger" href="{{url_for('categorie.deleteCat', cat_id=cat.id)}}">Supprimer</a></td>
		  {% endif %}
		</tr>
		{% endfor %}
		</tbody>
	</table>
	{% for page_num in cats.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if page_num %}
			{% if cats.page == page_num %}
				<a class="btn btn-info mb-4" href="{{ url_for('categorie.cat', page=page_num) }}">{{ page_num }}</a>
			{% else %}
				<a class="btn btn-outline-info mb-4" href="{{ url_for('categorie.cat', page=page_num) }}">{{ page_num }}</a>

			{% endif %}
		{% else %}
			...
		{% endif %}
	{% endfor %}
{% endblock content %}

route/templates/home.html
{% extends "layout.html" %}
{% block content %}
	<p>Bonjour, </p>
	{{val}}
{% endblock content %}

route/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <!-- Choose one v5 or v4 -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://raw.githack.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.js"></script>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

	{% if title %}
		<title>{{ title }}</title>
	{% else %}
		<title>Gestion Pointage</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="/">Gestion Pointage</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
				<a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
				{% if current_user.is_authenticated %}
	         	<div class="dropdown">
					<a class="nav-item nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Listes
					</a>
					<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
						<!-- <a class="dropdown-item" href="url_for('avion.list_avion')">Avion</a> -->
						<a class="dropdown-item" href="{{url_for('users.user')}}">Employe</a>
                        <a class="dropdown-item" href="{{url_for('categorie.cat')}}">Categorie</a>
						<a class="dropdown-item" href="{{url_for('pointage.list_pointage')}}">Pointage</a>
						<a class="dropdown-item" href="{{url_for('pointage.stat_user')}}">Montant à payer</a>
                        <a class="dropdown-item" href="{{url_for('pointage.detail_stat_user')}}">Statistiques</a>
						<a class="dropdown-item" href="{{url_for('configuration.list_config')}}">Configs</a>
						
					</div>
				</div>
				{% endif %}

				{% if current_user.is_authenticated and current_user.type_user == 1 %}
	        		<div class="dropdown">
						<a class="nav-item nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Ajout
						</a>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							<!-- <a class="dropdown-item" href="url_for('avion.new_avion')">Ajout Avion</a> -->
							<a class="dropdown-item" href="{{url_for('users.register')}}">Ajout employe</a>
							<a class="dropdown-item" href="{{url_for('categorie.add_cat')}}">Ajout categorie</a>
						</div>
					</div>
				{% endif %}
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	        	{% if current_user.is_authenticated %}
	        		<a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
	        	{% else %}
	        		<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
	        	{% endif %}
	          
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	    	{% with messages = get_flashed_messages(with_categories=true) %}
	    		{% if messages %}
	    			{% for category, message in messages %}
	    				<div class="alert alert-{{ category }}">
	    					{{ message }}
	    				</div>
	    			{% endfor %}
	    		{% endif %}
	    	{% endwith %}
	        {% block content %}{% endblock %}
	    </div>
	   	
	  </div>
	</main>

	

	<!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script> -->

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

route/templates/list_pointage.html
{% extends "layout.html" %}
{% block content %}
    <h1>Listes des pointages</h1>
    <table class="table">
        <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Iduser</th>
          <th scope="col">Matricule</th>
        </tr>
        </thead>
        <tbody>
        {% for pointage in points.items %}
        <tr>
          <td>{{pointage.id}}</td>
          <td>{{pointage.iduser}}</td>
          <td>{{pointage.employe.matricule}}</td>
          
          <td><a class="btn btn-outline-info" href="{{url_for('pointage.calcul_heure', user_id=pointage.iduser, pointage_id=pointage.id)}}">Voir details</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% for page_num in points.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if points.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('pointage.list_pointage', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('pointage.list_pointage', page=page_num) }}">{{ page_num }}</a>

            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

route/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.matricule.label(class="form-control-label") }}
                    {% if form.matricule.errors %}
                        {{ form.matricule(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.matricule.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.matricule(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
		<small class="text-muted">
            Need an account ? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now 
            </a>
        </small>
    </div>
{% endblock content %}

route/templates/user.html
{% extends "layout.html" %}
{% block content %}
	<h1>Listes des employees</h1>
	<table class="table">
		<thead>
		<tr>
		  <th scope="col">#</th>
		  <th scope="col">matricule</th>
		  <th scope="col">nom</th>
		  <th scope="col">prenom</th>
		  <th scope="col">date_naissance</th>
		  <th scope="col">date_embauche</th>
		  <th scope="col">date_fin_contrat</th>
		  <th scope="col">type_user</th>
		  <th scope="col">Categorie</th>
		</tr>
		</thead>
		<tbody>
		{% for user in users.items %}
		<tr>
		  <td>{{user.id}}</td>
		  <td>{{user.matricule}}</td>
		  <td>{{user.nom}}</td>
		  <td>{{user.prenom}}</td>
		  <td>{{user.date_naissance}}</td>
		  <td>{{user.date_embauche}}</td>
		  <td>{{user.date_fin_contrat}}</td>
		  <td>{{utils.type_user(user.type_user)}}</td>
		  <td>{{user.cat.nom}}</td>
		  {% if current_user.is_authenticated and current_user.type_user == 1 %}
		  <!-- url_for('trajet.update_trajet', portion_id=route.idportionroute) 
		  url_for('users.user_update', iduser=user.id)-->
		  <td><a class="btn btn-outline-success" href="{{url_for('users.updateUser', user_id=user.id)}}">Modifier</a></td>
		  <td><a class="btn btn-outline-success" href="{{url_for('pointage.add_pointage', user_id=user.id)}}">Nouveau Pointage</a></td>
		  {% endif %}
		</tr>
		{% endfor %}
		</tbody>
	</table>
	{% for page_num in users.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if page_num %}
			{% if users.page == page_num %}
				<a class="btn btn-info mb-4" href="{{ url_for('users.user', page=page_num) }}">{{ page_num }}</a>
			{% else %}
				<a class="btn btn-outline-info mb-4" href="{{ url_for('users.user', page=page_num) }}">{{ page_num }}</a>

			{% endif %}
		{% else %}
			...
		{% endif %}
	{% endfor %}
{% endblock content %}